import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "references/json-rpc/kaia/web-3-rpc",
    },
    {
      type: "category",
      label: "kaia",
      items: [
        {
          type: "doc",
          id: "references/json-rpc/kaia/account-created",
          label: "[Account] kaia_accountCreated",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/accounts",
          label: "[Account] kaia_accounts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/decode-account-key",
          label: "[Account] kaia_decodeAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-account-key",
          label: "[Account] kaia_getAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-code",
          label: "[Account] kaia_getCode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/encode-account-key",
          label: "[Account] kaia_encodeAccountKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-account",
          label: "[Account] kaia_getAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-balance",
          label: "[Account] kaia_getBalance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/sign",
          label: "[Account] kaia_sign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-count",
          label: "[Account] kaia_getTransactionCount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/is-contract-account",
          label: "[Account] kaia_isContractAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/block-number",
          label: "[Block] kaia_blockNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-by-hash",
          label: "[Block] kaia_getBlockByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-receipts",
          label: "[Block] kaia_getBlockReceipts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-transaction-count-by-number",
          label: "[Block] kaia_getBlockTransactionCountByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-with-consensus-info-by-number",
          label: "[Block] kaia_getBlockWithConsensusInfoByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-committee",
          label: "[Block] kaia_getCommittee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-committee-size",
          label: "[Block] kaia_getCommitteeSize",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-council",
          label: "[Block] kaia_getCouncil",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-council-size",
          label: "[Block] kaia_getCouncilSize",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-by-number",
          label: "[Block] kaia_getBlockByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-transaction-count-by-hash",
          label: "[Block] kaia_getBlockTransactionCountByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-header-by-number",
          label: "[Block] kaia_getHeaderByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-header-by-hash",
          label: "[Block] kaia_getHeaderByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-rewards",
          label: "[Block] kaia_getRewards",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-storage-at",
          label: "[Block] kaia_getStorageAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/syncing",
          label: "[Block] kaia_syncing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-with-consensus-info-by-number-range",
          label: "[Block] kaia_getBlockWithConsensusInfoByNumberRange",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-block-with-consensus-info-by-hash",
          label: "[Block] kaia_getBlockWithConsensusInfoByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/call",
          label: "[Transaction] kaia_call",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-decoded-anchoring-transaction-by-hash",
          label: "[Transaction] kaia_getDecodedAnchoringTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/estimate-gas",
          label: "[Transaction] kaia_estimateGas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-by-block-number-and-index",
          label: "[Transaction] kaia_getTransactionByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-by-sender-tx-hash",
          label: "[Transaction] kaia_getTransactionBySenderTxHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-by-block-hash-and-index",
          label: "[Transaction] kaia_getTransactionByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-by-hash",
          label: "[Transaction] kaia_getTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-receipt",
          label: "[Transaction] kaia_getTransactionReceipt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/send-raw-transaction",
          label: "[Transaction] kaia_sendRawTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/estimate-computation-cost",
          label: "[Transaction] kaia_estimateComputationCost",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/send-transaction",
          label: "[Transaction] kaia_sendTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/send-transaction-as-fee-payer",
          label: "[Transaction] kaia_sendTransactionAsFeePayer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/sign-transaction",
          label: "[Transaction] kaia_signTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/sign-transaction-as-fee-payer",
          label: "[Transaction] kaia_signTransactionAsFeePayer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/pending-transactions",
          label: "[Transaction] kaia_pendingTransactions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-transaction-receipt-by-sender-tx-hash",
          label: "[Transaction] kaia_getTransactionReceiptBySenderTxHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/create-access-list",
          label: "[Transaction] kaia_createAccessList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-raw-transaction-by-block-hash-and-index",
          label: "[Transaction] kaia_getRawTransactionByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-raw-transaction-by-hash",
          label: "[Transaction] kaia_getRawTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/resend",
          label: "[Transaction] kaia_resend",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-raw-transaction-by-block-number-and-index",
          label: "[Transaction] kaia_getRawTransactionByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/chain-id",
          label: "[Configuration] kaia_chainID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/client-version",
          label: "[Configuration] kaia_clientVersion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/gas-price-at",
          label: "[Configuration] kaia_gasPriceAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/gas-price",
          label: "[Configuration] kaia_gasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/is-parallel-db-write",
          label: "[Configuration] kaia_isParallelDBWrite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/is-sender-tx-hash-indexing-enabled",
          label: "[Configuration] kaia_isSenderTxHashIndexingEnabled",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/protocol-version",
          label: "[Configuration] kaia_protocolVersion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/rewardbase",
          label: "[Configuration] kaia_rewardbase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-chain-config",
          label: "[Configuration] kaia_getChainConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/fork-status",
          label: "[Configuration] kaia_forkStatus",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-filter-changes",
          label: "[Filter] kaia_getFilterChanges",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-filter-logs",
          label: "[Filter] kaia_getFilterLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/new-block-filter",
          label: "[Filter] kaia_newBlockFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/new-pending-transaction-filter",
          label: "[Filter] kaia_newPendingTransactionFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/uninstall-filter",
          label: "[Filter] kaia_uninstallFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/unsubscribe",
          label: "[Filter] kaia_unsubscribe",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-logs",
          label: "[Filter] kaia_getLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/subscribe",
          label: "[Filter] kaia_subscribe",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/new-filter",
          label: "[Filter] kaia_newFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/fee-history",
          label: "[Gas] kaia_feeHistory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/lower-bound-gas-price",
          label: "[Gas] kaia_lowerBoundGasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/upper-bound-gas-price",
          label: "[Gas] kaia_upperBoundGasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/max-priority-fee-per-gas",
          label: "[Gas] kaia_maxPriorityFeePerGas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/sha-3",
          label: "[Miscellaneous] kaia_sha3",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-staking-info",
          label: "[Miscellaneous] kaia_getStakingInfo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/recover-from-transaction",
          label: "[Miscellaneous] kaia_recoverFromTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/recover-from-message",
          label: "[Miscellaneous] kaia_recoverFromMessage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/get-proof",
          label: "[Miscellaneous] kaia_getProof",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "references/json-rpc/kaia/node-address",
          label: "[Miscellaneous] kaia_nodeAddress",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
